language: node_js
node_js:
- '4.2'
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - libcairo2-dev
    - libopencv-dev
    - libjpeg8-dev
    - libpng12-dev
    - libwebp-dev
    - libtiff4-dev
    - libexif-dev
    - libblas-dev
    - liblcms2-dev
    - libxml2-dev
    - libpango1.0-dev
    - build-essential
    - unicode-data
    - automake
    - gobject-introspection
    - gtk-doc-tools
    - libglib2.0-dev
    - swig
script:
- OUT_DIR=`pwd` TARGET=travis VERSION=`git describe --tags` ./build.sh
deploy:
  provider: heroku
  app: buildpack-stage
  on:
    repo: the-grid/heroku-buildpack-vips
    tags: true
  run:
  - TARGET=heroku VERSION=`git describe --tags` ./build.sh
  api_key:
    secure: d0nHKTBKplU/OABAv97Ib81XCtsKDvaTz5nb0vrkKOPu26BXcX8ubD0NOquPb2YwAKXjiCoU3GAjbHHZ3k3eZ0kFIhC6RPBMLA+tH05mMrHZOin6LHE7YH3ik+V6ajM9+v7awSCaFgdRy3qYlvEL22cy5m6hnu6wCTTw9LKtt7E=
env:
  global:
  - secure: GAGFo+xiGUk3WJ1bVXstBHhwlM8rKBY0ixI6To4GIJMrodcSXMX5M2Qx3IKVeZqz5ogqRqPqmvUqp1j8+8WeM+f7c+qbbflfqpfeVyacG43TM5yhsiyeUILbchlAWdNgwfmrZkvo2NItHonrYaJvbR8w1MRc0WHlt3v0Dy5apFE=
  - secure: vlp925+8JXVe0exjEPA6zQS6Eo1Ht3BtQS4lXciBSL8uLKWtfGwOGGABQ/Bo06Z1wZlH5AlynWmq3T9QlIuT/7enSBeGDf0KuO7VeEnujnxYty5JQuwdjNH0lHBiAtkkS13TIZaghOjJRvJUHDtvnlfh8U88PjVYe/xcMF0UDHs=
  - secure: bVlAElfvcuUVEweCKwfqRds6v9k7TISq/TKrt0iNLbzp+uqWw16PpxYrLLW6/qUkJ5Wlom7XxQBZfTeisTSvxMmmW1eJBS76+iYjVET6YHaWkS4i1DZoHL/yuFliM1LQu0FYJY3NZtIDgjGMHrXMY38c2Fsly1lJASVM9OyrjkM=
